version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      back_net:
        aliases:
          - fluentd        
      front_net:
        aliases:
          - fluentd

  elasticsearch:
    image: elasticsearch:5-alpine
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      back_net:
        aliases:
          - elasticsearch        
      front_net:
        aliases:
          - elasticsearch

  kibana:
    image: kibana:5
    ports:
      - "5601:5601"
    networks:
      back_net:
        aliases:
          - kibana        
      front_net:
        aliases:
          - kibana


networks:
  back_net:
  front_net:
